# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    config.vm.define "db01_machine" do |db|
      db.vm.box = "ubuntu/jammy64"
      db.vm.network "private_network", ip: "192.168.56.11"
      db.vm.hostname = "db01"
      db.vm.synced_folder "./backup", "/home/vagrant/backup"
      db.vm.provider "virtualbox" do |vb|
          vb.gui = false         
          vb.memory = "2048"
      end

      db.vm.provision "shell", inline: <<-SHELL
        apt-get update
        apt-get install -y postgresql postgresql-contrib
      SHELL
    end


    config.vm.define "app01_machine" do |app|
        app.vm.box = "ubuntu/jammy64"
        app.vm.network "private_network", ip: "192.168.56.10"
        # app.vm.network "forwarded_port", guest: 80, host: 8001
        # app.vm.network "forwarded_port", guest: 5000, host: 8002
        # app.vm.network "private_network", ip: "172.16.238.10"
        app.vm.hostname = "app01"
        app.vm.synced_folder "./jsonplaceholder-app", "/home/vagrant/app", exclude: ["./jsonplaceholder-app/flask-env"]
        app.vm.provider "virtualbox" do |vb|
           vb.gui = false
           vb.name = "app01"
           vb.memory = "2048"
        end

        app.vm.provision "shell", inline: <<-SHELL
          export DEBIAN_FRONTEND=noninteractive
          apt-get update
          apt-get -y install python3.10-venv python3-pip net-tools
          cd /home/vagrant/app
          venv_dir="/home/vagrant/app/flask-env"
          if [ -d "$venv_dir" ]; then
              echo "Le répertoire $venv_dir existe déjà."
              source /home/vagrant/app/flask-env/bin/activate
          else
              echo "Le répertoire $venv_dir n'existe pas. Création de l'environnement virtuel..."
              python3 -m venv $venv_dir
              source /home/vagrant/app/flask-env/bin/activate
              pip install -r requirement.txt
          fi
          # nohup python3 main.py & echo "Server web running"
          # python3 main.py
        SHELL
    end


    config.vm.define "backup_machine" do |backup|
        backup.vm.box = "ubuntu/jammy64"
        backup.vm.network "private_network", ip: "192.168.56.12"
        backup.vm.hostname = "backup01"
        backup.vm.provider "virtualbox" do |vb|
            vb.gui = false         
            vb.memory = "1024"
        end

        # config.vm.provision "shell", inline: <<-SHELL
        #   apt-get update
        #   apt-get upgrade
        #   apt-get install vsftpd
        #   apt-get update
        # SHELL
    end

  end
  
# J'ai eu un probleme quand j'ai donné les adresses 172.16, le range d'adresse IP était sur du 192.168
# vagrant status
# vagrant up app01